version: '3.7'
spring:
  application:
    name: media-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yaml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${SERVICE_PORT:8080}
  servlet:
    context-path: /media-service-sec

integration:
  profile:
    userService:
      name: ${USER_SERVICE_NAME:java-user-service}
      url: http://${USER_SERVICE_HOST:localhost}:${USER_SERVICE_PORT:8100}
      context-path: ${USER_SERVICE_PATH:}
    mediaService:
      name: ${MEDIA_SERVICE_NAME:media-service}
      url: http://${MEDIA_SERVICE_HOST:localhost}:${SERVICE_PORT:8080}
      context-path: ${MEDIA_SERVICE_PATH:/media-service-sec}

storage:
  root:
    path: ./media-storage